repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        language_version: python3.8
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: python3 -m pytest test/
        pass_filenames: false
        stages: [commit]
